import * as React from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = React.createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  fr: {
    'nav.dashboard': 'Tableau de bord',
    'nav.tickets': 'Tickets',
    'nav.assets': 'Appareils',
    'nav.alerts': 'Alertes',
    'nav.sites': 'Sites',
    'nav.app-center': 'App Center',
    'nav.kb': 'Base de connaissances',
    'nav.reports': 'Rapports',
    'nav.refer': 'Parrainer un ami',
    'nav.ai-center': 'Centre IA',
    'nav.admin': 'Administration',
    'nav.patches': 'Gestion des patchs',
    'nav.software': 'Inventaire logiciel',
    'nav.network': 'Découverte réseau',
    'nav.snmp': 'SNMP',
    'nav.scripts': 'Scripts',
    'nav.agent_download': 'Installer l\'Agent',
    'nav.desc_dashboard': 'Aperçu de la santé du système.',
    'nav.desc_rmm': 'Gestion à distance avancée.',
    'nav.desc_agent_download': 'Déployer l\'agent sur vos appareils.',
    'nav.desc_tickets': 'Gérer les demandes de support.',
    'nav.desc_sites': 'Gérer les organisations et emplacements.',
    'nav.desc_assets': 'Inventaire et gestion des terminaux.',
    'nav.desc_alerts': 'Notifications en temps réel.',
    'nav.desc_patches': 'Mises à jour système et tiers.',
    'nav.desc_scripts': 'Bibliothèque de scripts d\'automatisation.',
    'nav.desc_software': 'Suivre les logiciels et licences.',
    'nav.desc_app_center': 'Intégrations et place de marché.',
    'nav.desc_network': 'Scanner et cartographier le réseau local.',
    'nav.desc_snmp': 'Surveiller le matériel réseau via SNMP.',
    'nav.desc_kb': 'Documentation et guides de dépannage.',
    'nav.desc_reports': 'Analyses et rapports de conformité.',
    'nav.desc_refer': 'Partagez et gagnez des récompenses.',
    'nav.desc_ai_center': 'Insights propulsés par l\'IA.',
    'nav.desc_admin': 'Paramètres globaux et permissions.',
    'profile.settings': 'Paramètres',
    'profile.language': 'Langue',
    'profile.logout': 'Déconnexion',
    'status.optimal': 'Système Optimal',
    'status.optimal_desc': 'Tous les systèmes sont opérationnels. Aucun problème critique détecté.',
    'header.platform': 'Plateforme',
    'login.title': 'Connexion',
    'common.search': 'Rechercher...',
    'common.error_loading': 'Échec du chargement',
    'common.error_details': 'Échec des détails',
    'common.error_cancel': 'Échec annulation',
    'common.error_invitation': 'Échec invitation',
    'common.device': 'Appareil',
    'common.unknown': 'Inconnu',
    'common.invited': 'Invité',
    'common.send': 'Envoyer',
    'common.close': 'Fermer',
    'common.email': 'Email',
    'common.dashboard': 'Dashboard',
    'common.no_data': 'Aucune donnée',
    'dashboard.title': 'Tableau de bord',
    'dashboard.subtitle': 'Aperçu de votre infrastructure informatique et de la file d\'attente du support.',
    'dashboard.generate_report': 'Générer un rapport',
    'dashboard.open_tickets': 'Tickets Ouverts',
    'dashboard.managed_devices': 'Appareils Gérés',
    'dashboard.active_alerts': 'Alertes Actives',
    'dashboard.sla_compliance': 'Conformité SLA',
    'dashboard.vs_last': 'vs période précédente',
    'dashboard.performance': 'Performance du Service',
    'dashboard.performance_desc': 'Volume de tickets vs alertes système sur les 7 derniers jours.',
    'dashboard.critical_alerts': 'Alertes Critiques',
    'dashboard.attention_required': 'Attention immédiate requise',
    'dashboard.view_all_alerts': 'Voir toutes les alertes',
    'scripts.title': 'Bibliothèque de scripts',
    'scripts.subtitle': 'Gérez, organisez et exécutez vos scripts d\'automatisation.',
    'scripts.create': 'Créer un script',
    'scripts.browse_shared': 'Parcourir la bibliothèque partagée',
    'scripts.shared_library': 'Bibliothèque partagée',
    'scripts.my_scripts': 'Mes scripts',
    'scripts.clone': 'Faire une copie',
    'scripts.run_now': 'Exécuter maintenant',
    'scripts.variables': 'Variables',
    'scripts.add_variable': 'Ajouter une variable',
    'scripts.ai_generate': 'Générer le script',
    'scripts.ai_enable': 'Activer pour l\'assistant IA',
    'scripts.editor': 'Éditeur',
    'scripts.test_run': 'Exécution test',
    'scripts.target_os': 'OS cible',
    'scripts.category': 'Catégorie',
    'scripts.no_scripts': 'Aucun script trouvé',
    'agent.remote_active': 'FLUX Remote Active',
    'agent.remote_start': 'Connect via FLUX',
    'agent.remote_tooltip': 'Initiate an unattended remote session using FLUX.',
    'network.title': 'Découverte réseau',
    'network.subtitle': 'Scanner votre réseau local pour détecter et intégrer les appareils non gérés.',
    'network.start_scan': 'Démarrer le scan',
    'network.scanning': 'Scan en cours...',
    'network.select_proxy': 'Sélectionner un agent proxy',
    'network.proxy_agent': 'Agent proxy',
    'network.change_proxy': 'Changer',
    'network.scan_types': 'Types de scan',
    'network.ping_sweep': 'Balayage ping',
    'network.arp_lookup': 'Recherche ARP',
    'network.mdns_discovery': 'Découverte mDNS',
    'network.port_scan': 'Scan de ports',
    'network.custom_subnet': 'Sous-réseau personnalisé (CIDR)',
    'network.auto_detect': 'Détection automatique',
    'network.no_proxy_available': 'Aucun agent proxy en ligne. Installez l\'agent HypeRemote sur au moins un appareil du réseau cible.',
    'network.install_agent_first': 'Installer un agent',
    'network.empty_title': 'Prêt à scanner votre réseau',
    'network.empty_desc': 'La découverte nécessite un agent proxy : un appareil HypeRemote déjà géré sur le réseau cible.',
    'network.send_invitation': 'Envoyer une invitation d\'installation',
    'network.invitation_email': 'Email du destinataire',
    'network.invitation_message': 'Message (optionnel)',
    'network.invitation_sent': 'Invitation envoyée',
    'network.results_count': 'appareils trouvés',
    'network.managed': 'Géré',
    'network.unmanaged': 'Non géré',
    'network.device_type.computer': 'Ordinateur',
    'network.device_type.printer': 'Imprimante',
    'network.device_type.router': 'Routeur',
    'network.device_type.switch': 'Commutateur',
    'network.device_type.iot': 'IoT',
    'network.device_type.unknown': 'Inconnu',
    'network.scan_history': 'Historique des scans',
    'network.scan_failed': 'Scan échoué',
    'network.scan_cancelled': 'Scan annulé',
    'network.no_devices_found': 'Aucun appareil trouvé. Essayez d\'élargir le scan ou de vérifier le réseau de l\'agent proxy.',
    'network.proxy_offline': 'L\'agent proxy s\'est déconnecté pendant le scan',
    'network.scan_timeout': 'Délai du scan dépassé',
    'network.cancel_scan': 'Annuler',
    'network.mark_ignored': 'Marquer comme ignoré',
    'network.copy_ip': 'Copier IP',
  },
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.tickets': 'Tickets',
    'nav.assets': 'Devices',
    'nav.alerts': 'Alerts',
    'nav.sites': 'Sites',
    'nav.app-center': 'App Center',
    'nav.kb': 'Knowledge Base',
    'nav.reports': 'Reports',
    'nav.refer': 'Refer a Friend',
    'nav.ai-center': 'AI Center',
    'nav.admin': 'Admin',
    'nav.patches': 'Patch Management',
    'nav.software': 'Software Inventory',
    'nav.network': 'Network Discovery',
    'nav.snmp': 'SNMP',
    'nav.scripts': 'Scripts',
    'nav.agent_download': 'Install Agent',
    'nav.desc_dashboard': 'System health overview.',
    'nav.desc_rmm': 'Advanced remote management.',
    'nav.desc_agent_download': 'Deploy agent to your devices.',
    'nav.desc_tickets': 'Manage support requests.',
    'nav.desc_sites': 'Manage organizations and locations.',
    'nav.desc_assets': 'Inventory and endpoint management.',
    'nav.desc_alerts': 'Real-time notifications.',
    'nav.desc_patches': 'OS and third-party updates.',
    'nav.desc_scripts': 'Automation scripts library.',
    'nav.desc_software': 'Track software and licenses.',
    'nav.desc_app_center': 'Integrations and marketplace.',
    'nav.desc_network': 'Scan and map local network.',
    'nav.desc_snmp': 'Monitor network hardware via SNMP.',
    'nav.desc_kb': 'Documentation and troubleshooting guides.',
    'nav.desc_reports': 'Analytics and compliance reports.',
    'nav.desc_refer': 'Share and earn rewards.',
    'nav.desc_ai_center': 'AI-powered insights.',
    'nav.desc_admin': 'Global settings and permissions.',
    'profile.settings': 'Settings',
    'profile.language': 'Language',
    'profile.logout': 'Logout',
    'status.optimal': 'System Optimal',
    'status.optimal_desc': 'All systems are operational. No critical issues detected.',
    'header.platform': 'Platform',
    'login.title': 'Login',
    'common.search': 'Search...',
    'common.error_loading': 'Loading failed',
    'common.error_details': 'Details fetch failed',
    'common.error_cancel': 'Cancel failed',
    'common.error_invitation': 'Invitation failed',
    'common.device': 'Device',
    'common.unknown': 'Unknown',
    'common.invited': 'Invited',
    'common.send': 'Send',
    'common.close': 'Close',
    'common.email': 'Email',
    'common.dashboard': 'Dashboard',
    'common.no_data': 'No data available',
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Overview of your IT infrastructure and support queue.',
    'dashboard.generate_report': 'Generate Report',
    'dashboard.open_tickets': 'Open Tickets',
    'dashboard.managed_devices': 'Managed Devices',
    'dashboard.active_alerts': 'Active Alerts',
    'dashboard.sla_compliance': 'SLA Compliance',
    'dashboard.vs_last': 'vs last period',
    'dashboard.performance': 'Service Performance',
    'dashboard.performance_desc': 'Ticket volume vs System alerts over the last 7 days.',
    'dashboard.critical_alerts': 'Critical Alerts',
    'dashboard.attention_required': 'Immediate attention required',
    'dashboard.view_all_alerts': 'View All Alerts',
    'scripts.title': 'Script Library',
    'scripts.subtitle': 'Manage, organize, and execute automation scripts.',
    'scripts.create': 'Create Script',
    'scripts.browse_shared': 'Browse Shared Library',
    'scripts.shared_library': 'Shared Library',
    'scripts.my_scripts': 'My Scripts',
    'scripts.clone': 'Clone To library',
    'scripts.run_now': 'Run Now',
    'scripts.variables': 'Variables',
    'scripts.add_variable': 'Add Variable',
    'scripts.ai_generate': 'Generate Script',
    'scripts.ai_enable': 'Enable for AI Assistant',
    'scripts.editor': 'Editor',
    'scripts.test_run': 'Test Run',
    'scripts.target_os': 'Target OS',
    'scripts.category': 'Category',
    'scripts.no_scripts': 'No scripts found',
    'agent.remote_active': 'FLUX Remote Control Active',
    'agent.remote_start': 'Connect via FLUX',
    'agent.remote_tooltip': 'Control this PC directly using FLUX Unattended Access.',
    'network.title': 'Network Discovery',
    'network.subtitle': 'Scan your local network to find and onboard unmanaged devices.',
    'network.start_scan': 'Start scan',
    'network.scanning': 'Scanning...',
    'network.select_proxy': 'Select proxy agent',
    'network.proxy_agent': 'Proxy agent',
    'network.change_proxy': 'Change',
    'network.scan_types': 'Scan types',
    'network.ping_sweep': 'Ping sweep',
    'network.arp_lookup': 'ARP lookup',
    'network.mdns_discovery': 'mDNS discovery',
    'network.port_scan': 'Port scan',
    'network.custom_subnet': 'Custom subnet (CIDR)',
    'network.auto_detect': 'Auto-detect',
    'network.no_proxy_available': 'No eligible proxy agent online. Install the HypeRemote agent on at least one device on your target network.',
    'network.install_agent_first': 'Install an agent',
    'network.empty_title': 'Ready to scan your network',
    'network.empty_desc': 'Discovery requires a proxy agent — an already-managed HypeRemote device on the target LAN.',
    'network.send_invitation': 'Send install invitation',
    'network.invitation_email': 'Recipient email',
    'network.invitation_message': 'Message (optional)',
    'network.invitation_sent': 'Invitation sent',
    'network.results_count': 'devices found',
    'network.managed': 'Managed',
    'network.unmanaged': 'Unmanaged',
    'network.device_type.computer': 'Computer',
    'network.device_type.printer': 'Printer',
    'network.device_type.router': 'Router',
    'network.device_type.switch': 'Switch',
    'network.device_type.iot': 'IoT',
    'network.device_type.unknown': 'Unknown',
    'network.scan_history': 'Scan history',
    'network.scan_failed': 'Scan failed',
    'network.scan_cancelled': 'Scan cancelled',
    'network.no_devices_found': 'No devices found. Try widening the scan or checking the proxy agent\'s network.',
    'network.proxy_offline': 'Proxy agent went offline during scan',
    'network.scan_timeout': 'Scan timed out',
    'network.cancel_scan': 'Cancel',
    'network.mark_ignored': 'Mark as ignored',
    'network.copy_ip': 'Copy IP',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = React.useState<Language>('fr');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = React.useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
